#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.3.9f1_947e1ea5aa8d"
#define UNITY_VERSION_FULL_NICE "2018.3.9f1 (947e1ea5aa8d)"
#define UNITY_VERSION_BLD 9731614
#define UNITY_VERSION_DATE 1552645163
#define UNITY_VERSION_WIN "2018.3.9.9731614"
#define UNITY_VERSION_BRANCH "2018.3/release"
